settings:
  reward: sparse
  show_gui: False
  dt: 0.005
  max_episode_steps: 300
  action_frequency: 30
  simulation_frequency: 240
  random_obj_position: True
observation:
  with_tactile_sensor: False
  with_force: False
  with_gripper_width: False
  with_noise: False
  relative: True
action:
  with_gripper_width: False
objects:
  table:
    urdf_path: "table/table.urdf"
    base_position: [0.5, 0, -0.6]
tacto:
  width: 64
  height: 64
  visualize_gui: False
sawyer_gripper:
  robot_params:
    urdf_path: "robots/sawyer_wsg50.urdf"
    use_fixed_base: True
  init_state:
    end_effector:
      position: [0.35, 0, 0.40]
      orientation: [-0.7071, 0.7071, 0, 0]
    gripper_width: 0.080
debug_camera:
  cameraDistance: 0.6
  cameraYaw: 15.
  cameraPitch: -20.
  cameraTargetPosition: [0.5, 0, 0.08]
cameras: ???