defaults:
  - sawyer_base_env
  - cameras: 
    - view_1
    - view_2

observation:
  with_gripper_width: True
action:
  with_gripper_width: True
sawyer_gripper:
  init_state:
    gripper_width: 0.090

objects:
  door:
    urdf_path: "door/urdf/door.urdf"
    base_position: [0.70, 0., 0.25]
    base_orientation: [ 0, 0, -0.7071068, 0.7071068 ]
    use_fixed_base: True

debug_camera:
  cameraDistance: 0.6
  cameraYaw: 15.
  cameraPitch: -20.
  cameraTargetPosition: [0.5, 0, 0.08]